//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Alarm.h
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#if !defined(_ALARM_H)
#define _ALARM_H


class Alarm {
public:
	void alarmGeven();
private:
	int alarm;
};

#endif  //_ALARM_H
