//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Alarm.cpp
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#include "Alarm.h"

void Alarm::alarmGeven() {

}

