//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : CANcontroller.h
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//

#if !defined(_CANCONTROLLER_H)
#define _CANCONTROLLER_H

#include "CANFormat.h"
#include "Toestand.h"

class CANcontroller
{  private:
	int positie;

public:
	void inlezen();
	void verzenden();
	void printen();
};

#endif  //_CANCONTROLLER_H
