//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : CANcontroller.cpp
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//

#include "CANcontroller.h"

void inlezen();


void verzenden();
void printen();



