//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Display.cpp
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#include "Display.h"

void Display::afbeelden() {
//variabelen in af te beelden volgorde
//verdeling in velden
//
}

