//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Display.h
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//

#if !defined(_DISPLAY_H)
#define _DISPLAY_H

class Display {
public:
	void afbeelden();
private:
	int indeling;
};

#endif  //_DISPLAY_H
