//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : GPS-format.cpp
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#include "GPS-format.h"

void GPS-format::omrekenen() {

}

