//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : GPS-format.h
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#if !defined(_GPS-FORMAT_H)
#define _GPS-FORMAT_H


class GPS-format {
public:
	void omrekenen();
private:
	int NBreedte;
	int OLengte;
};

#endif  //_GPS-FORMAT_H
