//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Klok.cpp
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#include "Klok.h"

void Klok::instellen() {

}

