//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Klok.h
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#if !defined(_KLOK_H)
#define _KLOK_H


class Klok {
public:
	void instellen();
private:
	int tijdstip;
};

#endif  //_KLOK_H
