//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Koerslog.h
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#if !defined(_KOERSLOG_H)
#define _KOERSLOG_H

#include "GPS-format.h"
#include "Klok.h"
#include "Waypoint.h"
#include "memSetup.h"
#include "logInUit.h"
#include "CANcontroller.h"

class Koerslog : public GPS-format, public Klok, public Waypoint, public memSetup, public logInUit, public CANcontroller {
public:
	void saveTrack();
	void reverseTrack();
	void memManage();
private:
	int actief;
};

#endif  //_KOERSLOG_H
