//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Koerslog.cpp
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#include "Koerslog.h"

void Koerslog::saveTrack() {

}

void Koerslog::reverseTrack() {

}

void Koerslog::memManage() {

}

