//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : memSetup.cpp
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#include "memSetup.h"

void memSetup::setUp() {

}

