//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : memSetup.h
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#if !defined(_MEMSETUP_H)
#define _MEMSETUP_H


class memSetup {
public:
	void setUp();
private:
	int logmem;
	int routemem;
	int waypointmem;
};

#endif  //_MEMSETUP_H
