//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Stuurautomaat.cpp
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#include "Stuurautomaat.h"

void Stuurautomaat::functieInstellen() {

}

void Stuurautomaat::positieInlezen() {

}

void Stuurautomaat::berekenHeading() {

}

void Stuurautomaat::getBearing() {

}

void Stuurautomaat::XTE() {

}

void Stuurautomaat::berekenSnelheid() {

}

void Stuurautomaat::distance() {

}

void Stuurautomaat::roerSignaal() {

}

void Stuurautomaat::vasteKoersCorrigeren() {

}

void Stuurautomaat::alarmeren() {

}

