//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Stuurautomaat.h
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#if !defined(_STUURAUTOMAAT_H)
#define _STUURAUTOMAAT_H

#include "Route.h"
#include "Alarm.h"
#include "CANcontroller.h"

class Stuurautomaat : public Route, public Alarm, public CANcontroller {
public:
	void functieInstellen();
	void positieInlezen();
	void berekenHeading();
	void getBearing();
	void XTE();
	void berekenSnelheid();
	void distance();
	void roerSignaal();
	void vasteKoersCorrigeren();
	void alarmeren();
private:
	int roerstand;
	int functie;
	int heading;
	int bearing;
	int XTE;
	int behoudenSnelheid;
};

#endif  //_STUURAUTOMAAT_H
