//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Toestand.cpp
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//

#include "Toestand.h"

void Toestand::toplicht_schakelen()
{  if (toplicht_aan = true) toplicht_aan = false;
   else toplicht_aan = true; 	
}
void Toestand::ankerlicht_schakelen()
{  if (ankerlicht_aan = true) ankerlicht_aan = false;
   else ankerlicht_aan = true;
}
void Toestand::stoomlicht_schakelen()
{  if (stoomlicht_aan = true) stoomlicht_aan = false;
   else stoomlicht_aan = true;
}
void Toestand::navigatielicht_schakelen()
{  if (navigatielicht_aan = true) navigatielicht_aan = false;
   else navigatielicht_aan = true;
}
void Toestand::deklicht_schakelen()
{  if (deklicht_aan = true) deklicht_aan = false;
   else deklicht_aan = true;
}
void Toestand::navigatiealarm_schakelen()
{  if (navigatiealarm_aan = true) navigatiealarm_aan = false;
   else navigatiealarm_aan = true;
}
void Toestand::wateralarm_schakelen()
{  if (wateralarm_aan = true) wateralarm_aan = false;
   else wateralarm_aan = true;
}
double Toestand::bericht_ID_ophogen (double bericht_ID)
{  bericht_ID++;
   if (bericht_ID>1000000) bericht_ID=0;
}
void Toestand::zet_OL(int* grad_OL, int* min_OL)
{  graden_OL=*grad_OL;
   minuten_OL=*min_OL;
}

void Toestand::zet_NB(int* grad_NB, int* min_NB)
{  graden_NB=*grad_NB;
   minuten_NB=*min_NB;
}
int Toestand::get_roerstand()
{  return roerstand;
}
void Toestand::zet_roerstand(int graden)
{  roerstand=graden;
}