//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : vaartuigcontroller
//  @ File Name : Waypoint.cpp
//  @ Date : 6-12-2012
//  @ Author : S.J. Koster
//
//


#include "Waypoint.h"

void Waypoint::aanmaken() {

}

void Waypoint::bewerken() {

}

void Waypoint::save() {

}

